name: Build Docker Images

on:
  push:
    branches:
      - pub-repo

jobs:
  quick-start:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: build docker
        shell: bash
        run: make slice-ubuntu && docker build demo --tag slice-demo

  quick-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: quick build
        shell: bash
        run: |
          make setup
          make all

  build-sliceloaderonly:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: setup
        shell: bash
        run: |
          make setup
          make slice-ubuntu
      - name: install riscv toolchain
        run: make install
      - name: build sliceloader
        shell: bash
        run: make slice-hss/Default-qemu/hss-envm-wrapper.bin
      - name: download guest linux
        shell: bash
        run: make guest-linux-prebuilt
      - name: build sd image
        shell: bash
        run: |
          make payload-build
          make qemu-prebuilt

